spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: "123456."
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.2.101
    username: admin
    password: 1111
    virtual-host: /usian
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/